/* SNO 4, l'île Carrefour : le second monde de la saga, bâti sur le vodou
   haïtien, dans le froid de l'Archipel des Neuf. Trois ensembles de
   personnages : la famille Gede (Baron Samedi, Maman Brigitte et les morts),
   les lwa du péristyle (Rada et Petwo : Legba, Mèt Kalfou, Damballah,
   Erzulie…) et le lakou Jean-Louis (les vivants, quatre générations).
   Lu par saga.js, qui l'ajoute au reste. Pas d'import.

   Le vodou est une religion vivante. Les lwa ne sont pas des monstres ni des
   démons : ce sont des puissances, servies, aimées, redoutées. Voir la page
   « Ce que ce monde refuse ». Les mots kreyòl sont donnés avec leur sens. */

// ── La bible du second monde ──
export const BIBLE_SNO4 = [
  {
    id: 'sno4', monde: 'sno4',
    titre: 'Le second monde : SNO 4, l\'île Carrefour',
    texte: [
      `SNO 4 est l'île où se croisent toutes les routes de l'Archipel des Neuf, celles de la mer et celles des morts. Les gens de l'île l'appellent Lil Kalfou, l'île Carrefour. Il y fait aussi froid que partout ailleurs : la banquise l'enserre neuf mois sur douze, le vent ne tombe pas, et la neige est grise de la cendre des forges.`,
      `Il y a cent dix hivers, un trois-mâts venu du sud, La Délivrance, a été poussé par une tempête à travers le brouillard jusqu'ici, et pris dans la glace. À son bord voyageaient des femmes et des hommes libres, des Haïtiens partis chercher une terre. Ils ont survécu au froid avec ce qu'ils avaient emporté : leurs lwa. Le houngan Dieubon Jean-Louis a planté le grand mât du navire dans la glace, et il est devenu le poto mitan, le pilier du péristyle, par où les esprits descendent.`,
      `Les lwa ont suivi leurs serviteurs « à travers les eaux », comme ils l'ont toujours fait. Ils se sont habitués au froid. On trace les vèvè à la cendre sur la neige, faute de farine de maïs. Le kleren gèle dans les bouteilles, et on le réchauffe dans la bouche avant de le cracher en offrande. Baron Samedi garde un cimetière de neige, aux croix couvertes de givre.`,
      `Depuis dix-neuf hivers, quelque chose ne va plus. Sur SNO 7, l'île voisine, un roi a cloué le temps, et personne n'y meurt vraiment. Les âmes qui devraient passer s'entassent au grand carrefour de SNO 4, dans la neige, et attendent. Les routes des morts sont bouchées. Baron Samedi n'a pas creusé une seule tombe depuis, et il enrage, à sa manière : en riant de plus en plus fort.`,
    ],
  },
  {
    id: 'vodou', monde: 'sno4',
    titre: 'Le vodou de l\'île',
    texte: [
      `Les lwa (les esprits) sont servis par familles, les nanchon (« nations »). Les Rada sont les lwa venus d'Afrique : doux, anciens, blancs, comme Legba, Damballah et Erzulie Freda. Les Petwo sont nés en Haïti, dans le feu de la révolte : chauds, rapides, rouges, comme Mèt Kalfou, Erzulie Dantor et Ogou. Les Gede sont les morts, la famille de Baron Samedi, qui rient de tout, et surtout de la mort.`,
      `On sert les lwa au péristyle, autour du poto mitan. Le houngan (le prêtre) et la mambo (la prêtresse) dirigent la cérémonie, les ounsi (les initiés) chantent, les tambours appellent. On trace au sol le vèvè du lwa qu'on appelle : son dessin, son nom écrit en lignes. On commence toujours par Legba, qui ouvre la barrière entre les deux mondes : « Papa Legba, louvri baryè a pou mwen » (ouvre-moi la barrière).`,
      `Quand un lwa vient, il « monte » un serviteur, comme un cavalier son cheval : le chwal, possédé, parle et agit comme lui. Les morts passent un an et un jour « anba dlo », sous l'eau, avant qu'on les rappelle dans un govi, une jarre de terre, d'où ils conseillent les vivants. Au bout du chemin, sous les eaux, il y a Ginen, la terre des ancêtres.`,
      `Le bokor « sert des deux mains » : pour le bien et pour le mal, contre paiement. Il peut voler un ti bon anj (la part de l'âme qui fait la personne) et le garder dans une bouteille. Un corps qu'on a privé de son âme devient un zonbi : un esclave sans volonté, la pire chose qui puisse arriver sur une île de gens libres. Le sel le réveille.`,
    ],
  },
  {
    id: 'sno4-jeu', monde: 'sno4',
    titre: 'Ce que le vodou change au jeu',
    texte: [
      `L'héroïne est Anaïse Jean-Louis, dix-neuf ans, ounsi du péristyle de son père. Son dessin vient du héros, en version féminine, avec le foulard des servantes. Elle porte une machette d'Ogou au lieu de l'épée. Sa sœur jumelle, Anisse, est morte il y a un an, et son âme ne peut pas passer.`,
      `Les vèvè se tracent en marchant. Les traces sont toujours le récit, mais ici on les écrit soi-même : une mambo montre un vèvè, et Anaïse le marche dans la neige. Quand le dessin se referme, le lwa vient. Avec la cendre de la forge, le vèvè reste ; sans elle, la neige l'efface en quarante secondes.`,
      `La possession : un lwa monte Anaïse pour vingt secondes, et le jeu change de main.
- Gede : elle se déhanche, rit, se moque de tout, ne peut plus frapper, mais les zonbi s'arrêtent pour l'écouter.
- Ogou : la machette frappe deux fois plus fort et le froid ne mord plus.
- Damballah : elle ne parle plus, avance lentement et traverse la glace mince sans la casser.
- Legba : elle boite, appuyée sur une canne, mais toute barrière s'ouvre devant elle.
- Mèt Kalfou, la nuit : elle voit les âmes du carrefour, mais la malchance la suit (les loups la trouvent).`,
      `Le reste du vodou entre aussi dans le jeu :
- Les offrandes, trouvées dans l'île, appellent chacune un lwa : le café et la pipe pour Legba, le kleren aux vingt et un piments pour Baron, le parfum pour Freda, le couteau pour Dantor, un œuf sur un lit de farine pour Damballah, le rhum versé sur le feu pour Ogou.
- Le sel réveille un zonbi.
- Les tambours se mêlent à la musique : le yanvalou pour Damballah, le petwo pour Kalfou, le banda pour les Gede.`,
    ],
  },
  {
    id: 'sno4-refus', monde: 'sno4',
    titre: 'Ce que ce monde refuse',
    texte: [
      `Pas de « poupée vaudou » à épingles : c'est un cliché de cinéma, pas le vodou haïtien. Pas de zombies en hordes affamées : le zonbi est une victime, un être libre qu'on a réduit en esclavage, et on le délivre au lieu de l'abattre. Personne ne combat un lwa à l'épée : on le sert, on le prie, on négocie, on lui tient tête parfois, mais on ne le tue pas.`,
      `Le mal, sur SNO 4, vient d'un homme, Lucien Deux-Mains, le bokor, pas du vodou. Les lwa gardent leurs noms, leurs attributs et leurs caractères de tradition : Baron Samedi est drôle, grossier, juste. Legba est vieux et bienveillant, Kalfou dangereux sans être mauvais, Freda pleure toujours. Le jeu a une seule invention, signalée : Gede Frèt, un Gede né sur l'île.`,
      `Les vèvè du jeu sont inspirés des vrais, simplifiés en pixels, jamais tournés en dérision. À faire relire, avant de les mettre dans le jeu, par quelqu'un qui sert les lwa. L'humour des Gede reste dans ce qui convient aux dix à quinze ans : des blagues sur le nez, le froid, la mort et les vivants trop sérieux.`,
    ],
  },
  {
    id: 'sno4-liens', monde: 'sno4',
    titre: 'Les liens entre les deux mondes',
    texte: [
      `La nuit de SNO 7 bouche les routes des morts. C'est le nœud des deux histoires : tant que Kári n'a pas arraché le clou de Nortia, la sœur d'Anaïse ne peut pas passer. Les deux héros finissent par se croiser au grand carrefour, chacun avec sa moitié de la solution.`,
      `Baron Samedi et Vanth, les deux passeurs, l'un en haut-de-forme, l'autre ailée, jouent aux cartes sur un cercueil la nuit, à la taverne de Sidrún sur SNO 8. L'enjeu, ce sont les âmes en attente. Vanth perd toujours, et Baron triche toujours.`,
      `Erzulie Freda a vu la grande Freya de SNO 7 dans un rêve et pleure de jalousie : Freda, Freya, Uni, trois noms qui se ressemblent trop. Ayida Wedo, l'arc-en-ciel, et Jörmungandr, le serpent du monde, se connaissent depuis le début : l'un entoure le ciel, l'autre la mer.`,
      `Lucien Deux-Mains et Kingvi sont la même peur sous deux formes : le roi a cloué le temps pour ne pas mourir, le bokor boit les années des âmes en bouteille. Baron les a tous les deux dans son registre, et la date n'y est pas encore écrite.`,
    ],
  },
  {
    id: 'sno4-chrono', monde: 'sno4',
    titre: 'Chronologie de SNO 4',
    liste: [
      ['−140', 'Naissance de Dieubon Jean-Louis, à Jacmel, en Haïti.'],
      ['−110', 'La Délivrance quitte Haïti vers le sud. Une tempête l\'emporte vers le nord, à travers le brouillard. Elle se prend dans la banquise de SNO 4.'],
      ['−109', 'Le grand mât est planté dans la glace : il devient le poto mitan. Premier vèvè tracé à la cendre.'],
      ['−108', 'Le matelot Fortuné meurt gelé, le premier mort de l\'île. Il revient comme Gede Frèt.'],
      ['−95', 'Naissance de Sò Élise.'],
      ['−90', 'Naissance de Lucien, son frère, qui deviendra le bokor.'],
      ['−72', 'Mort de Célimène, la mambo. Première femme enterrée dans la neige : Maman Brigitte prend sa croix.'],
      ['−65', 'Naissance de Sauveur.'],
      ['−60', 'Naissance de Clotilde.'],
      ['−40', 'Lucien est chassé du péristyle. Il bâtit sa maison aux bouteilles sur la banquise.'],
      ['−19', 'La nuit tombe sur SNO 7. Sur SNO 4, les âmes commencent à s\'entasser au carrefour. Baron range sa pelle.'],
      ['−19', 'Naissance d\'Anaïse et d\'Anisse, les marasa (les jumelles), la nuit même.'],
      ['−12', 'Clotilde disparaît. On la revoit un an plus tard, marchant sur la glace, les yeux baissés : zonbi.'],
      ['−1', 'Anisse meurt de froid en allant porter du café à Legba. Son âme rejoint la foule du carrefour.'],
      ['0', 'Un an et un jour après : on devrait la retirer d\'en bas de l\'eau. Mais il n\'y a pas de passage. Anaïse part chercher pourquoi.'],
    ],
  },
];

// ── Les trois nouveaux ensembles ──
export const FAMILIES_SNO4 = [
  { id: 'gede', monde: 'sno4', nom: 'Les Gede', devise: 'Tout le monde passe par chez nous.', about: 'La famille des morts, autour de Baron Samedi et de Maman Brigitte : ils gardent les cimetières, rient de tout, et décident qui peut mourir. Sur SNO 4, ils n\'ont plus rien à enterrer depuis dix-neuf hivers.' },
  { id: 'lwa', monde: 'sno4', nom: 'Les lwa du péristyle', devise: 'Louvri baryè a. (Ouvre la barrière.)', about: 'Les grands lwa servis au péristyle de l\'île, Rada (doux, anciens) et Petwo (chauds, rapides) : le gardien de la barrière et celui du carrefour, le serpent et l\'arc-en-ciel, les deux Erzulie, la mer, le fer, l\'eau douce, les arbres.' },
  { id: 'jeanlouis', monde: 'sno4', nom: 'Le lakou Jean-Louis', devise: 'Nou la. (Nous sommes là.)', about: 'Les descendants du houngan de La Délivrance : une famille de serviteurs des lwa, de forgerons, de marins, et un bokor. Quatre générations sur la glace.' },
];

// ── Les personnages ──
export const PEOPLE_SNO4 = [
  // ══ Les Gede ══
  {
    id: 'baron', nom: 'Baron Samedi', surnom: 'le Maître du cimetière', famille: 'gede', gen: 1, sexe: 'm',
    conjoints: ['brigitte'], statut: 'immortel', vie: '—',
    role: 'Le chef des Gede, gardien de la mort. C\'est lui qui creuse, ou qui refuse de creuser.',
    lieu: 'Le cimetière du Baron, sur SNO 4 ; la taverne de Sidrún, les nuits de cartes',
    magie: 'Aucun mort n\'entre dans la terre sans lui. Il peut refuser la mort à un vivant. Il guérit ceux qu\'il ne veut pas encore.',
    sprite: { corps: 'homme', tete: 'haut-de-forme', objet: 'pelle', accent: 'cigare' },
    voix: 'Nasillarde (du coton dans le nez), rapide, grossière, drôle ; il éclate de rire au milieu des phrases graves.',
    bio: [
      `Haut-de-forme, queue-de-pie noire, lunettes de soleil dont il a cassé un verre (pour voir les deux mondes), du coton dans les narines comme les morts qu'on prépare, un cigare et une bouteille de kleren où macèrent vingt et un piments. Il est le premier mort de chaque cimetière, la croix au centre, et rien ne passe la terre sans son accord.`,
      `Sur SNO 4, il a trouvé un cimetière de neige, et il l'a aimé tout de suite : « Ici au moins, ils se conservent ! » Il y a enterré les passagers de La Délivrance un à un, avec des blagues pour chacun.`,
      `Depuis dix-neuf hivers, il n'enterre plus personne. Les âmes ne descendent plus : elles s'entassent au carrefour, au-dessus de la neige, à attendre. Il a rangé sa pelle et il tient son registre ouvert à une page où il manque une date, celle d'un roi assis sous une roche, sur l'île d'à côté. Il rit plus fort que jamais, et ceux qui le connaissent savent que c'est mauvais signe.`,
      `Il triche aux cartes avec Vanth, la passeuse étrusque, et il ne s'en cache pas : « Elle le sait, chérie. C'est pour ça qu'elle revient. »`,
    ],
    lignes: ['Pas un mort à enterrer, et pourtant ça meurt partout !', 'Tu veux passer, ti fi ? Paie le passage. Avec quoi ? Avec la vérité.', 'Ha ! Personne ne m\'échappe. Il a juste un peu de retard.'],
  },
  {
    id: 'brigitte', nom: 'Maman Brigitte', surnom: 'la Gardienne des tombes', famille: 'gede', gen: 1, sexe: 'f',
    conjoints: ['baron'], statut: 'immortel', vie: '—',
    role: 'L\'épouse de Baron, mère des Gede, gardienne des croix et des tombes.',
    lieu: 'Le cimetière du Baron : la croix de Célimène',
    magie: 'Elle garde chaque tombe où une femme a été enterrée la première. Elle guérit avec le rhum aux piments, frotté sur la peau.',
    sprite: { corps: 'femme', tete: 'foulard', objet: 'croix', blanc: true },
    voix: 'Rauque, directe, elle jure comme un marin et console comme une mère.',
    bio: [
      `La seule lwa à la peau pâle et aux cheveux roux. Les gens disent qu'elle est venue de loin, d'une île du nord, il y a longtemps. Le froid de SNO 4 ne la dérange pas : « J'ai connu pire. »`,
      `Sa croix se dresse sur la tombe de la première femme enterrée dans un cimetière. Sur SNO 4, c'est celle de Célimène, la mambo de La Délivrance. Brigitte lui parle tous les soirs.`,
      `Elle seule fait taire Baron. Elle ne supporte pas la foule d'âmes du carrefour : des enfants y attendent dans le vent, et elle descend leur chanter des chansons qu'aucun vivant n'entend.`,
    ],
    lignes: ['Viens là, toi. Tu as froid jusqu\'à l\'âme, ça se voit.', 'Ta sœur ? Je la connais. Elle chante faux. Elle chante quand même.'],
  },
  {
    id: 'lacroix', nom: 'Baron La Croix', surnom: 'le Baron qui rit', famille: 'gede', gen: 1, sexe: 'm',
    statut: 'immortel', vie: '—', parents: [],
    role: 'Un autre visage du Baron : le moqueur, celui des carrefours de cimetière.',
    lieu: 'Le cimetière', magie: 'Il se moque de la mort jusqu\'à ce qu\'elle recule.',
    sprite: { corps: 'homme', tete: 'haut-de-forme', objet: 'croix' },
    voix: 'Aiguë, ironique.',
    bio: [`Certains disent que Baron Samedi, Baron La Croix et Baron Cimetière sont trois frères ; d'autres, trois visages d'un même Baron. Sur SNO 4, on les voit ensemble certaines nuits, alignés devant la croix, et ils ne sont pas d'accord entre eux.`],
    lignes: ['La mort, c\'est sérieux ? Ha ! C\'est elle qui a peur de nous.'],
  },
  {
    id: 'cimetiere', nom: 'Baron Cimetière', surnom: 'le Baron qui garde', famille: 'gede', gen: 1, sexe: 'm',
    statut: 'immortel', vie: '—',
    role: 'Le troisième visage : celui qui garde les portes du cimetière.',
    lieu: 'La grille du cimetière', magie: 'Rien n\'entre ni ne sort du cimetière sans qu\'il le sache.',
    sprite: { corps: 'vieux', tete: 'haut-de-forme', objet: 'canne' },
    voix: 'Lente, sèche, administrative.',
    bio: [`Le plus sérieux des trois. Il compte. Il a compté les âmes du carrefour : quatre cent douze ce matin, dont trente de SNO 7, un viking aux dents de loup parmi eux.`],
    lignes: ['Quatre cent douze ce matin. Quatre cent treize avec ta sœur.'],
  },
  {
    id: 'nibo', nom: 'Gede Nibo', surnom: 'le Premier mort', famille: 'gede', gen: 2, sexe: 'm',
    parents: ['baron', 'brigitte'], conjoints: ['masaka'], statut: 'immortel', vie: '—',
    role: 'Un jeune homme mort de violence, adopté par Baron et Brigitte. Il parle pour les morts.',
    lieu: 'Le cimetière, le carrefour', magie: 'Il fait parler les morts qui n\'ont pas de voix.',
    sprite: { corps: 'ado', tete: 'haut-de-forme', objet: 'bouteille' },
    voix: 'Gouailleuse, rapide ; il dit tout haut ce que les vivants pensent tout bas.',
    bio: [`Jeune, élégant, mal élevé. Il se poudre le visage de cendre et porte un haut-de-forme trop grand. Il circule parmi les âmes du carrefour et porte leurs messages, en les déformant un peu pour rire. C'est par lui qu'Anaïse entend sa sœur la première fois.`],
    lignes: ['Ta sœur te fait dire qu\'elle a froid aux pieds. Et que tu lui dois une écharpe.', 'Moi ? Mort ? Depuis longtemps, ma belle. Et en pleine forme.'],
  },
  {
    id: 'masaka', nom: 'Gede Masaka', surnom: 'la Fossoyeuse', famille: 'gede', gen: 2, sexe: 'f',
    conjoints: ['nibo'], statut: 'immortel', vie: '—',
    role: 'La compagne de Nibo. Elle aide à creuser, quand on creuse encore.',
    lieu: 'Le cimetière', magie: 'Elle connaît les feuilles qui soignent et celles qui tuent.',
    sprite: { corps: 'femme', tete: 'foulard', objet: 'pelle' },
    voix: 'Grave, lasse, très drôle sans sourire.',
    bio: [`Elle porte un sac de feuilles et une pelle qui n'a pas servi depuis dix-neuf hivers. Elle s'ennuie. Elle a commencé à creuser une tombe pour le roi de SNO 7, « pour être prête ».`],
    lignes: ['Je creuse pour un roi. Il ne le sait pas encore.'],
  },
  {
    id: 'zaranyen', nom: 'Gede Zaranyen', surnom: 'l\'Araignée', famille: 'gede', gen: 2, sexe: 'm',
    parents: ['baron', 'brigitte'], statut: 'immortel', vie: '—',
    role: 'Le Gede araignée, qui tisse entre les tombes.',
    lieu: 'Entre les croix', magie: 'Ses fils de givre relient les tombes : il sent qui marche dessus.',
    sprite: { corps: 'enfant', tete: 'haut-de-forme' },
    voix: 'Un chuchotement qui court.',
    bio: [`Il tisse des fils de givre entre les croix du cimetière. Quand Anaïse marche dans le cimetière, chaque pas fait vibrer un fil, et Zaranyen raconte à Baron ce qu'elle a dans le cœur.`],
    lignes: ['Tu marches doucement. Tu as peur de réveiller quelqu\'un ? Il n\'y a personne. Plus personne.'],
  },
  {
    id: 'gedefret', nom: 'Gede Frèt', surnom: 'le Gede du froid (invention du jeu)', famille: 'gede', gen: 3, sexe: 'm',
    parents: ['nibo', 'masaka'], statut: 'immortel', vie: '−108',
    role: 'Fortuné, le matelot de La Délivrance mort gelé, le premier mort de l\'île, revenu Gede. Le seul lwa né sur SNO 4.',
    lieu: 'La banquise, près de l\'épave', magie: 'Il gèle ce qu\'il touche, et il dégèle ce qu\'il aime.',
    sprite: { corps: 'homme', tete: 'haut-de-forme', blanc: true },
    voix: 'Il claque des dents en parlant. Il chante des chansons de marin en kreyòl.',
    bio: [
      `Fortuné avait dix-sept ans quand La Délivrance s'est prise dans la glace. Il est mort la deuxième nuit, en faisant le guet sur la vergue. Baron est venu le chercher en riant, et lui a dit : « Toi, tu restes. Ils vont avoir besoin d'un Gede qui connaît le froid. »`,
      `Il a du givre sous le nez à la place du coton, et une moustache de glaçons. Les Gede l'ont adopté comme un petit. C'est le seul lwa qui soit né sur l'île, et le seul que le jeu ait inventé.`,
    ],
    lignes: ['Brrr. Cent huit hivers que j\'ai froid. Et alors ? Je suis mort, pas malade.', 'Tu veux traverser la glace ? Marche où je marche. Là. Non, là.'],
  },

  // ══ Les lwa du péristyle ══
  {
    id: 'legba', nom: 'Papa Legba', surnom: 'Atibon Legba, le Gardien de la barrière', famille: 'lwa', gen: 1, sexe: 'm',
    statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'Le premier qu\'on salue : il ouvre la barrière entre le monde des vivants et celui des lwa.',
    lieu: 'La Barrière, sur la grève de SNO 4', magie: 'Il ouvre les portes, les chemins, les bouches. Sans lui, aucun autre lwa ne peut venir.',
    sprite: { corps: 'vieux', tete: 'chapeau', objet: 'canne' },
    voix: 'Lente, très douce, amusée ; il parle par proverbes.',
    bio: [
      `Un vieil homme qui boite, un chapeau de paille, une pipe, une canne, un sac en bandoulière et un chien maigre à ses pieds. On le croirait faible ; il tient la porte de tous les mondes.`,
      `Sur SNO 4, il est assis sur un tonneau, à la Barrière, deux mâts couverts de givre plantés sur la grève, là où les naufragés ont posé le pied. On lui laisse du café, qui gèle dans la tasse, et il le boit quand même.`,
      `C'est en lui portant son café qu'Anisse est morte de froid, il y a un an. Legba ne s'en remet pas. Il n'a pas pu la faire passer : la barrière des morts n'est pas la sienne, elle est à son autre visage, Kalfou, et Kalfou a fermé.`,
    ],
    lignes: ['Ayibobo, pitit. Tu as apporté le café ?', 'La barrière est ouverte pour toi. Celle d\'en dessous, non. Ce n\'est pas la mienne.', 'Dèyè mòn, gen mòn. (Derrière les montagnes, d\'autres montagnes.)'],
  },
  {
    id: 'kalfou', nom: 'Mèt Kalfou', surnom: 'Maître Carrefour', famille: 'lwa', gen: 1, sexe: 'm',
    statut: 'immortel', vie: '—', nation: 'Petwo',
    role: 'L\'autre visage du carrefour : il garde la nuit, la malchance, et le passage des morts.',
    lieu: 'Le grand carrefour, au milieu de l\'île, la nuit', magie: 'Il ouvre et ferme les chemins de la nuit. Il tient les âmes qui attendent. Il porte malheur à qui le néglige.',
    sprite: { corps: 'geant', tete: 'masque', objet: 'canne', accent: 'oeil', echelle: 2 },
    voix: 'Basse, sans hâte, sans chaleur. Il ne répète jamais.',
    bio: [
      `Si Legba est le carrefour au lever du jour, Kalfou est le carrefour à minuit. Grand, sombre, son rouge à lui est un œil qui brille sous le bord de la capuche. On ne l'appelle pas pour rien, et on ne le renvoie pas sans lui avoir donné quelque chose.`,
      `Il n'est pas mauvais ; il est exact. Quand la nuit de SNO 7 a bouché les routes des morts, il a fermé son carrefour pour qu'aucune âme ne se perde dans le noir d'à côté. Elles attendent donc chez lui, quatre cent douze, dans la neige, debout.`,
      `Il négocie. Il demande toujours un prix qu'on n'avait pas prévu.`,
    ],
    lignes: ['Les morts attendent chez moi. Personne ne les a perdus. Personne ne les a rendus.', 'Je rouvrirai quand le roi d\'à côté lâchera son clou. Ou si tu me paies.', 'Le prix ? Une nuit de ta vie. Tu ne sauras pas laquelle.'],
  },
  {
    id: 'damballah', nom: 'Damballah Wedo', surnom: 'le Serpent blanc', famille: 'lwa', gen: 1, sexe: 'm',
    conjoints: ['ayida'], statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'Le serpent du ciel, le plus ancien, père de la sagesse. Il ne parle pas : il siffle.',
    lieu: 'Le mapou gelé', magie: 'Paix, pureté, sagesse. Sa présence calme le vent ; ceux qu\'il monte rampent et sifflent.',
    sprite: { corps: 'serpent', blanc: true },
    voix: 'Aucun mot. Des sifflements que le chwal traduit, après.',
    bio: [`Blanc, très vieux, enroulé dans les branches du mapou gelé. Il aime le blanc, les œufs posés sur un petit tas de farine, et le silence. Sur SNO 4, la neige est son vêtement. Quand il descend, le vent tombe une minute, sur toute l'île.`],
    lignes: ['Ssssss…', '(traduit par le chwal) Tout ce qui est fermé a été ouvert une fois.'],
  },
  {
    id: 'ayida', nom: 'Ayida Wedo', surnom: 'l\'Arc-en-ciel', famille: 'lwa', gen: 1, sexe: 'f',
    conjoints: ['damballah'], statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'L\'épouse de Damballah, le serpent arc-en-ciel.',
    lieu: 'Le ciel, au-dessus du mapou', magie: 'Elle tient le ciel et la terre ensemble. Dans le froid, son arc se voit la nuit, en lueurs tramées.',
    sprite: { corps: 'serpent' },
    voix: 'Un bruissement de couleurs (le jeu n\'en a que trois : il les trame).',
    bio: [`Elle s'enroule avec Damballah autour du monde. Sur SNO 4, on la voit les nuits les plus froides : une lueur qui se courbe au-dessus de l'île, ce que les vikings appellent les lumières du nord. Elle connaît Jörmungandr, le serpent de mer de l'archipel ; ils ne se parlent pas, mais ils se tiennent.`],
    lignes: [],
  },
  {
    id: 'freda', nom: 'Erzulie Freda', surnom: 'la Dame', famille: 'lwa', gen: 2, sexe: 'f',
    statut: 'immortel', vie: '—', nation: 'Rada', soeurs: ['dantor'],
    role: 'L\'amour, la beauté, le luxe ; elle finit toujours en larmes, parce que rien n\'est assez.',
    lieu: 'Le miroir de glace du péristyle', magie: 'Elle donne l\'amour, et elle le reprend.',
    sprite: { corps: 'femme', tete: 'voile', accent: 'coeur' },
    voix: 'Douce, coquette, puis brisée ; elle pleure à la fin de chaque visite.',
    bio: [
      `Elle aime les parfums, les bijoux, les gâteaux, et les hommes qui la courtisent. On lui réserve une chambre au péristyle, avec un miroir. Sur SNO 4, le miroir est un bloc de glace poli, et elle s'y voit pâle.`,
      `Elle a vu dans un rêve la grande Freya de SNO 7, et elle ne s'en remet pas : « Freda, Freya. Qui a copié qui ? »`,
    ],
    lignes: ['Tu m\'as apporté du parfum ? Il a gelé. Comme tout, ici.', 'Freya… Elle a mon nom, presque. Elle a mon visage, presque. Presque, c\'est le pire.'],
  },
  {
    id: 'dantor', nom: 'Erzulie Dantor', surnom: 'la Mère au couteau', famille: 'lwa', gen: 2, sexe: 'f',
    statut: 'immortel', vie: '—', nation: 'Petwo', soeurs: ['freda'],
    role: 'La mère qui protège, fière, féroce ; elle porte des cicatrices sur la joue et un couteau.',
    lieu: 'Partout où un enfant est en danger', magie: 'Elle protège les mères, les enfants et les femmes seules. Elle ne parle pas : elle fait « kè-kè-kè ».',
    sprite: { corps: 'femme', tete: 'foulard', objet: 'couteau', accent: 'oeil' },
    voix: 'Elle n\'a pas de langue. Elle claque : kè-kè-kè. Le chwal traduit.',
    bio: [`Les cicatrices sur sa joue, elle les a reçues en se battant pour les siens. Elle porte un enfant sur un bras et un couteau dans l'autre main. Sur SNO 4, elle veille sur Anaïse depuis la mort de sa jumelle : quand le bokor approche, la neige se met à saigner.`],
    lignes: ['Kè-kè-kè !', '(traduit par le chwal) Personne ne met ma fille en bouteille.'],
  },
  {
    id: 'agwe', nom: 'Agwe Tawoyo', surnom: 'l\'Amiral de la mer', famille: 'lwa', gen: 2, sexe: 'm',
    conjoints: ['sirene'], statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'Le maître de la mer, des navires et des marins. Il a guidé La Délivrance jusqu\'ici.',
    lieu: 'Sous la banquise ; sur sa barque, l\'Imamou', magie: 'Il commande à la mer et à la glace qui la couvre. On lui envoie ses offrandes sur une barque qu\'on pousse au large.',
    sprite: { corps: 'homme', tete: 'casque', objet: 'rame' },
    voix: 'Militaire, polie, un peu sourde, comme sous l\'eau.',
    bio: [
      `Un amiral en uniforme, couvert de coquillages. Il n'a pas voulu laisser La Délivrance couler dans la tempête : il l'a poussée jusqu'à la seule terre qu'il voyait, et la terre était gelée. Il s'en excuse depuis cent dix hivers.`,
      `Il connaît le Survivant de SNO 9 : c'est lui qui a porté son navire, au temps du Grand Givre. Il connaît aussi le chemin d'en bas de l'eau, vers Ginen.`,
    ],
    lignes: ['Je vous ai menés à terre. Je ne savais pas qu\'elle était si froide.', 'Ta sœur est sous ma glace, avec les autres. Je la garde. Je ne peux pas la rendre.'],
  },
  {
    id: 'sirene', nom: 'La Sirène', surnom: 'la Dame des eaux', famille: 'lwa', gen: 2, sexe: 'f',
    conjoints: ['agwe'], statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'L\'épouse d\'Agwe, qui chante sous l\'eau et attire les vivants en bas.',
    lieu: 'Sous la glace, près de l\'épave', magie: 'Elle emmène sous l\'eau ceux qu\'elle aime, et ils en reviennent savants. On l\'entend chanter à travers la glace.',
    sprite: { corps: 'sirene', tete: 'tresses', objet: 'trompette' },
    voix: 'Un chant, avec des mots dedans.',
    bio: [`Mi-femme, mi-poisson, une trompette et un peigne. Elle chante sous la banquise, et ceux qui collent l'oreille à la glace entendent parfois leur nom. Elle a appris à Anaïse, enfant, à retenir son souffle.`],
    lignes: ['Viens en bas, ma belle. En bas, il fait moins froid qu\'on croit.'],
  },
  {
    id: 'ogou', nom: 'Ogou Feray', surnom: 'le Forgeron de guerre', famille: 'lwa', gen: 2, sexe: 'm',
    statut: 'immortel', vie: '—', nation: 'Rada et Petwo',
    role: 'Le fer, la guerre, la forge. Le seul feu toujours allumé de l\'île est à lui.',
    lieu: 'La forge d\'Ogou', magie: 'Il donne la force et le courage ; ceux qu\'il monte versent du rhum sur le feu et ne se brûlent pas.',
    sprite: { corps: 'homme', tete: 'foulard', objet: 'machette', large: true },
    voix: 'Forte, bourrue, généreuse ; il donne des ordres.',
    bio: [`Soldat et forgeron, un foulard rouge sur la tête (rouge : la seule couleur qu'on lui accorde ici, un pixel), une machette à la main. À la forge du lakou, le feu ne s'est jamais éteint depuis le naufrage : c'est le sien. Il a forgé la machette d'Anaïse à partir d'un clou du pont de La Délivrance.`],
    lignes: ['Lève le bras. Plus haut. Le froid, c\'est un ennemi comme un autre.', 'Rhum sur le feu ! Voilà. Maintenant, tu as chaud.'],
  },
  {
    id: 'simbi', nom: 'Simbi', surnom: 'le Serpent des sources', famille: 'lwa', gen: 2, sexe: 'x',
    statut: 'immortel', vie: '—', nation: 'Rada et Petwo',
    role: 'Le gardien de l\'eau douce, de la magie et des passages entre les nations.',
    lieu: 'La source chaude, sous la glace', magie: 'Garde la seule eau qui ne gèle pas. Ceux qui boivent à sa source comprennent le langage des lwa.',
    sprite: { corps: 'serpent' },
    voix: 'Claire, rapide, savante.',
    bio: [`Simbi vit dans une source chaude qui fume sous la glace, au nord de l'île, la seule eau qui ne gèle jamais. Il passe d'une nation à l'autre comme l'eau passe sous la glace. C'est lui qui sait comment on retire un mort « d'en bas de l'eau » quand le passage est fermé.`],
    lignes: ['Il y a toujours un passage sous la glace. Il est juste froid.'],
  },
  {
    id: 'loko', nom: 'Loko Atisou', surnom: 'le Premier houngan', famille: 'lwa', gen: 1, sexe: 'm',
    conjoints: ['ayizan'], statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'L\'esprit des arbres et des guérisons, patron des houngan ; il vit dans le poto mitan.',
    lieu: 'Le poto mitan du péristyle (le grand mât de La Délivrance)', magie: 'Guérit, juge, donne le savoir des feuilles.',
    sprite: { corps: 'vieux', tete: 'chapeau', objet: 'asson' },
    voix: 'Patiente, de juge.',
    bio: [`Le premier houngan, gardien des arbres sacrés. Il n'y avait pas d'arbre sacré sur SNO 4, alors il s'est installé dans le grand mât planté dans la glace. Quand le vent souffle, le mât craque, et c'est Loko qui parle.`],
    lignes: ['Le mât était un arbre, avant. Un arbre se souvient.'],
  },
  {
    id: 'ayizan', nom: 'Ayizan Velekete', surnom: 'la Première mambo', famille: 'lwa', gen: 1, sexe: 'f',
    conjoints: ['loko'], statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'La patronne des mambo, de l\'initiation et du marché.',
    lieu: 'Le marché sur la glace', magie: 'Elle garde l\'initiation (le kanzo) et purifie. Sa frange de palmier est ici une branche de sapin gelée.',
    sprite: { corps: 'vieille', tete: 'foulard', objet: 'baton' },
    voix: 'Sévère, juste, elle ne rit jamais et elle aime beaucoup.',
    bio: [`Il n'y a pas de palmier sur SNO 4. Pour l'initiation, Ayizan a pris une branche de sapin, l'a fendue en franges, et elle a dit : « Ça ira. » Elle tient, à l'aube d'une nuit sans aube, un marché sur la glace où vivants et morts échangent ce qu'ils ont.`],
    lignes: ['Tu veux devenir mambo ? Alors tu brûleras un peu. Ici, ça fait du bien.'],
  },
  {
    id: 'granbwa', nom: 'Gran Bwa', surnom: 'la Grande Forêt', famille: 'lwa', gen: 2, sexe: 'm',
    statut: 'immortel', vie: '—', nation: 'Petwo',
    role: 'L\'esprit de la forêt sauvage, des feuilles et des racines.',
    lieu: 'Le mapou gelé', magie: 'Toutes les feuilles qui soignent sont à lui. Il a fait pousser un mapou dans la glace.',
    sprite: { corps: 'geant', tete: 'cornes', echelle: 2 },
    voix: 'Un bruit de branches.',
    bio: [`Un mapou ne pousse pas dans le froid. Gran Bwa en a fait pousser un quand même, d'une graine que Célimène gardait dans son corsage. L'arbre est mort et vivant à la fois, gelé, immense, et Damballah dort dans ses branches.`],
    lignes: [],
  },
  {
    id: 'marasa', nom: 'Les Marasa', surnom: 'les Jumeaux divins', famille: 'lwa', gen: 1, sexe: 'x',
    statut: 'immortel', vie: '—', nation: 'Rada',
    role: 'Les enfants jumeaux sacrés, salués avant tous les autres lwa après Legba.',
    lieu: 'Partout où il y a des jumeaux', magie: 'Plus puissants que tous les lwa, parce qu\'ils sont deux et enfants. Ils veillent sur Anaïse et Anisse.',
    sprite: { corps: 'enfant', tete: 'tresses' },
    voix: 'Deux voix d\'enfants qui parlent ensemble.',
    bio: [`On les nourrit en premier, dans des assiettes doubles. Ils ont regardé naître Anaïse et Anisse la nuit où le temps s'est cloué sur SNO 7, et ils n'acceptent pas qu'on sépare des jumelles. Ce sont eux qui ont mis Anaïse en route.`],
    lignes: ['Deux. Pas un. Deux.', 'Va chercher ta moitié.'],
  },

  // ══ Le lakou Jean-Louis ══
  {
    id: 'dieubon', nom: 'Dieubon Jean-Louis', surnom: 'Papa Bon, le houngan de La Délivrance', famille: 'jeanlouis', gen: 1, sexe: 'm',
    conjoints: ['celimene'], statut: 'mort', vie: '−140 – −80',
    role: 'Le houngan qui a planté le mât dans la glace.',
    lieu: 'Son govi, au péristyle', magie: 'Houngan asogwe, le plus haut grade. Il parle encore depuis son govi.',
    sprite: { corps: 'vieux', tete: 'chapeau', objet: 'asson' },
    voix: 'Depuis la jarre : lointaine, tranquille, avec l\'accent de Jacmel.',
    bio: [`Il était parti de Jacmel avec quarante personnes, un asson et un tambour. Il a vu la glace se refermer sur le navire et il a dit : « Bon. On va servir ici. » Il a fait planter le mât, tracé le premier vèvè à la cendre, et appelé Legba dans une langue que le vent ne connaissait pas. Legba est venu. Mort, il a été retiré d'en bas de l'eau et parle depuis son govi.`],
    lignes: ['Depuis la jarre, on voit loin. Ta sœur est au carrefour. Et le carrefour est plein.'],
  },
  {
    id: 'celimene', nom: 'Célimène', surnom: 'la Mambo, la première croix', famille: 'jeanlouis', gen: 1, sexe: 'f',
    conjoints: ['dieubon'], statut: 'mort', vie: '−135 – −72',
    role: 'La mambo de La Délivrance. Première femme enterrée dans la neige : sa tombe porte la croix de Maman Brigitte.',
    lieu: 'Le cimetière du Baron', magie: 'Elle savait les chants. Elle gardait une graine de mapou dans son corsage.',
    sprite: { corps: 'vieille', tete: 'foulard', objet: 'asson' },
    voix: 'Morte, elle chante plus qu\'elle ne parle.',
    bio: [`C'est elle qui a appris aux enfants de l'île les chants de Legba, de Damballah et d'Erzulie. Elle a semé la graine de mapou dans la glace, et Gran Bwa l'a fait pousser. Brigitte veille sur sa tombe et lui parle chaque soir.`],
    lignes: [],
  },
  {
    id: 'toussaint', nom: 'Capitaine Toussaint Vertus', surnom: 'le Capitaine', famille: 'jeanlouis', gen: 1, sexe: 'm',
    statut: 'mort-vivant', vie: '−145 – −100',
    role: 'Le capitaine de La Délivrance, serviteur d\'Agwe. Son fantôme tient encore la barre de l\'épave.',
    lieu: 'L\'épave, dans la banquise', magie: 'Il n\'a jamais quitté son navire.',
    sprite: { corps: 'homme', tete: 'casque', objet: 'rame' },
    voix: 'Les ordres d\'un capitaine dans la tempête, cent ans après.',
    bio: [`Il a refusé de quitter son navire quand la glace l'a pris. Il est mort à la barre, et il y est toujours. Certaines nuits, quand Agwe l'appelle, l'épave craque comme si elle allait repartir.`],
    lignes: ['Larguez ! Larguez, je vous dis ! … Ah. La glace.'],
  },
  {
    id: 'elise', nom: 'Sò Élise', surnom: 'la Mambo du lakou', famille: 'jeanlouis', gen: 2, sexe: 'f',
    parents: ['dieubon', 'celimene'], conjoints: ['ezechiel'], statut: 'mort', vie: '−95 – −30',
    role: 'La mambo qui a tenu le péristyle après ses parents. Elle a chassé son frère, le bokor.',
    lieu: 'Son govi', magie: 'Mambo asogwe. Elle traçait les vèvè les yeux fermés.',
    sprite: { corps: 'femme', tete: 'foulard', objet: 'asson' },
    voix: 'Ferme, rapide, sans détour.',
    bio: [`Elle a dirigé le péristyle quarante ans. Elle aimait son frère Lucien plus que tout, jusqu'au jour où elle a trouvé une bouteille qui parlait sous son lit. Elle l'a chassé du lakou devant tout le monde, et elle ne l'a plus jamais nommé.`],
    lignes: ['Ne prononce pas son nom dans le péristyle. Dehors, si tu veux. Et crache après.'],
  },
  {
    id: 'ezechiel', nom: 'Ezéchiel Marcelin', surnom: 'le Forgeron', famille: 'jeanlouis', gen: 2, sexe: 'm',
    conjoints: ['elise'], statut: 'mort', vie: '−98 – −35',
    role: 'Le forgeron, serviteur d\'Ogou, qui a gardé le feu.',
    lieu: 'La forge d\'Ogou', magie: 'Ogou le montait souvent : alors il prenait le fer rouge à pleines mains.',
    sprite: { corps: 'homme', tete: 'foulard', objet: 'marteau', large: true },
    voix: '—',
    bio: [`Un matelot de La Délivrance, devenu forgeron à force de récupérer les clous du navire. Il a promis à Ogou de ne jamais laisser mourir le feu. Ses fils le gardent depuis sa mort.`],
    lignes: [],
  },
  {
    id: 'lucien', nom: 'Lucien Deux-Mains', surnom: 'le Bokor', famille: 'jeanlouis', gen: 2, sexe: 'm',
    parents: ['dieubon', 'celimene'], statut: 'vivant', vie: '−90 –',
    role: 'Le frère d\'Élise, chassé du péristyle : il met les âmes en bouteille et boit leurs années.',
    lieu: 'La maison aux bouteilles, sur la banquise', magie: 'Il « sert des deux mains ». Il prend les âmes perdues du carrefour, les garde en bouteille et vit de leurs années. Il fait des zonbi.',
    sprite: { corps: 'vieux', tete: 'chapeau', objet: 'bouteille' },
    voix: 'Mielleuse, raisonnable, persuasive ; il a toujours une bonne raison.',
    bio: [
      `Le cadet de Dieubon, le plus doué, celui qui entendait les lwa avant même qu'on les appelle. Il a eu peur de la mort très tôt, en voyant les naufragés geler un à un. Il a appris, seul, ce que les houngan refusent d'apprendre.`,
      `Chassé du lakou, il a bâti sa maison sur la banquise avec les planches de la cale. Des centaines de bouteilles pendent à ses avant-toits et tintent dans le vent : chacune garde une âme. Il a quatre-vingt-dix hivers et le visage d'un homme de cinquante.`,
      `La nuit de SNO 7 a été pour lui une fortune : les âmes s'entassent au carrefour, perdues, faciles à prendre. Il en a pris beaucoup. Il voudrait prendre celle d'Anisse : une âme de jumelle, « ça vaut dix ans ».`,
      `Il ressemble à Kingvi plus qu'il ne le croit. Baron le sait, et il attend.`,
    ],
    lignes: ['Ta sœur ? Je peux la garder pour toi. Au chaud. Dans le verre.', 'Moi, mauvais ? J\'ai peur de mourir, c\'est tout. Comme toi. Comme tout le monde.', 'Le Baron m\'attend ? Qu\'il attende. Il sait faire.'],
  },
  {
    id: 'sauveur', nom: 'Houngan Sauveur Marcelin', surnom: 'le Père', famille: 'jeanlouis', gen: 3, sexe: 'm',
    parents: ['elise', 'ezechiel'], conjoints: ['mirlande'], statut: 'vivant', vie: '−65 –',
    role: 'Le houngan du péristyle aujourd\'hui, père d\'Anaïse.',
    lieu: 'Le péristyle', magie: 'Houngan. Legba lui parle. Kalfou ne lui répond plus.',
    sprite: { corps: 'homme', tete: 'foulard', objet: 'asson' },
    voix: 'Calme, fatiguée ; il cache sa peur derrière les règles.',
    bio: [`Il a perdu une fille l'an dernier, et sa sœur Clotilde il y a douze ans. Il tient le péristyle par devoir. Il a demandé à Kalfou de rouvrir le passage, a offert tout ce qu'il avait, et Kalfou n'a pas répondu. Il ne veut pas qu'Anaïse parte.`],
    lignes: ['Les lwa ne nous doivent rien, Anaïse. C\'est nous qui leur devons.', 'Si tu pars, salue Legba d\'abord. Toujours Legba d\'abord.'],
  },
  {
    id: 'mirlande', nom: 'Mirlande', surnom: 'la Mère', famille: 'jeanlouis', gen: 3, sexe: 'f',
    conjoints: ['sauveur'], statut: 'vivant', vie: '−50 –', origine: 'Une famille de marins de l\'île',
    role: 'La mère des jumelles, ounsi, chanteuse du péristyle.',
    lieu: 'Le lakou', magie: 'Elle mène les chants. Erzulie Dantor la monte parfois.',
    sprite: { corps: 'femme', tete: 'foulard' },
    voix: 'Chantée, cassée depuis un an.',
    bio: [`Elle n'a plus chanté depuis la mort d'Anisse. Dantor l'a montée deux fois cette année, et chaque fois le chwal a pointé le couteau vers la banquise, vers la maison aux bouteilles.`],
    lignes: ['Ramène-la, ou reviens seule. Mais reviens.'],
  },
  {
    id: 'clotilde', nom: 'Clotilde', surnom: 'la Zonbi de la banquise', famille: 'jeanlouis', gen: 3, sexe: 'f',
    parents: ['elise', 'ezechiel'], statut: 'mort-vivant', vie: '−60 –',
    role: 'La sœur de Sauveur, prise par son oncle Lucien : zonbi, elle marche sur la glace sans âme.',
    lieu: 'La banquise, entre l\'épave et la maison aux bouteilles', magie: 'Aucune. Son ti bon anj est dans une bouteille. Le sel la réveillera.',
    sprite: { corps: 'femme', tete: 'voile' },
    voix: 'Zonbi, elle ne parle pas : elle répète un mot. Réveillée par le sel, elle parle trop vite, comme quelqu\'un qui rattrape douze ans.',
    bio: [
      `Elle était la plus gaie du lakou. Elle allait porter à manger à son oncle chassé, en cachette, parce qu'elle ne croyait pas ce qu'on disait de lui. Un soir, elle n'est pas revenue.`,
      `Elle marche sur la banquise depuis, les yeux baissés, un fagot sur le dos, de la maison aux bouteilles à l'épave et retour. Elle a un fils, Ti-Jo, qui la voit passer et qu'elle ne voit pas. Si Anaïse lui fait goûter du sel, elle se réveille.`,
    ],
    lignes: ['… bwa … bwa … (… bois … bois …)', '(réveillée) Ti-Jo ? Où est Ti-Jo ? Quelle année ? Non, ne me dis pas.'],
  },
  {
    id: 'jeanjacques', nom: 'Jean-Jacques', surnom: 'le Marin d\'en bas', famille: 'jeanlouis', gen: 3, sexe: 'm',
    parents: ['elise', 'ezechiel'], statut: 'mort', vie: '−58 – −30',
    role: 'Le frère marin, parti avec Agwe : il vit sous l\'eau, chez La Sirène.',
    lieu: 'Anba dlo, sous la banquise', magie: 'La Sirène l\'a gardé ; il connaît le chemin d\'en bas.',
    sprite: { corps: 'homme', tete: 'nue', objet: 'rame' },
    voix: 'Des bulles et des rires.',
    bio: [`Il est parti un matin pêcher dans un trou de la glace et n'est pas remonté. On dit que La Sirène l'a emmené. Il guide les âmes sous la glace, quand il y a encore un passage.`],
    lignes: ['Tonton Jean-Jacques, en bas, à ton service. Retiens ton souffle, et suis la lumière froide.'],
  },
  {
    id: 'anaise', nom: 'Anaïse Jean-Louis', surnom: 'l\'Héroïne de SNO 4', famille: 'jeanlouis', gen: 4, sexe: 'f',
    parents: ['sauveur', 'mirlande'], statut: 'vivant', vie: '−19 –',
    role: 'La jumelle qui reste. On la joue sur SNO 4.',
    lieu: 'Le lakou, puis toute l\'île', magie: 'Ounsi : les lwa la montent. Elle trace les vèvè en marchant. Les Marasa veillent sur elle.',
    sprite: { corps: 'femme', tete: 'foulard', objet: 'machette' },
    voix: 'Têtue, drôle, polie avec les lwa, insolente avec les vivants.',
    bio: [
      `Née la nuit où le temps s'est arrêté sur SNO 7, une minute avant sa sœur. Ounsi depuis ses douze ans. Elle trace les vèvè plus droit que son père et chante plus faux que sa mère.`,
      `L'an dernier, c'est elle qui devait porter le café à Legba, ce soir-là. Elle avait mal à la gorge et Anisse y est allée à sa place. On a retrouvé Anisse le lendemain, assise contre le tonneau de Legba, gelée, la tasse pleine.`,
      `Un an et un jour plus tard, on aurait dû retirer sa sœur d'en bas de l'eau. Le passage est fermé. Anaïse prend la machette d'Ogou, le sac de sa grand-mère et une poignée de sel, et elle part.`,
    ],
    lignes: ['Papa Legba, louvri baryè a pou mwen.', 'Je ne viens pas prier. Je viens chercher ma sœur.', 'Deux. Pas un. Deux.'],
  },
  {
    id: 'anisse', nom: 'Anisse Jean-Louis', surnom: 'la Jumelle au carrefour', famille: 'jeanlouis', gen: 4, sexe: 'f',
    parents: ['sauveur', 'mirlande'], statut: 'mort-vivant', vie: '−19 – −1',
    role: 'La jumelle morte de froid ; son âme attend au carrefour.',
    lieu: 'Le grand carrefour', magie: 'Âme en attente. Lucien veut la mettre en bouteille.',
    sprite: { corps: 'femme', tete: 'foulard', blanc: true },
    voix: 'Comme sa sœur, en plus doux, et de plus en plus loin.',
    bio: [`Elle est morte en portant le café de sa sœur. Elle n'en veut à personne, et ça rend tout le monde fou. Au carrefour, elle s'occupe des enfants morts qui attendent avec elle, elle leur apprend les chants. Elle commence à oublier son propre nom.`],
    lignes: ['Tu as mis du sucre dans le café ? Legba n\'aime pas le sucre.', 'Ne pleure pas. Ici, ça gèle les yeux.', 'Comment je m\'appelais, déjà ? Dis-le, toi.'],
  },
  {
    id: 'tijo', nom: 'Ti-Jo', surnom: 'le Fils de la zonbi', famille: 'jeanlouis', gen: 4, sexe: 'm',
    parents: ['clotilde'], statut: 'vivant', vie: '−12 –',
    role: 'Le fils de Clotilde, élevé par Sauveur. Il suit Anaïse partout.',
    lieu: 'Le lakou', magie: 'Il voit les Gede. Il ne leur a jamais dit.',
    sprite: { corps: 'enfant', tete: 'nue' },
    voix: 'Vite, plein de questions, il imite Baron très bien.',
    bio: [`Douze ans, né l'année où sa mère a disparu. Il la voit passer sur la banquise et lui fait signe tous les jours. Il garde du sel dans ses poches depuis qu'il sait ce que le sel fait aux zonbi, mais il n'a jamais osé.`],
    lignes: ['Tu vas chez le Baron ? Je peux venir ? Je sais faire sa voix. Ha ! Ha !', 'Tiens, du sel. Pour maman. Si tu la vois.'],
  },
];

// ── Les lieux de SNO 4 ──
export const PLACES_SNO4 = [
  { id: 'barriere', nom: 'La Barrière de Legba', ile: 'SNO 4', nouveau: true, about: 'Sur la grève, deux mâts couverts de givre plantés dans la neige, là où les naufragés ont posé le pied. Legba y est assis sur un tonneau, avec son chien.', x: 0.16, y: 0.55 },
  { id: 'delivrance', nom: 'L\'épave de La Délivrance', ile: 'SNO 4', nouveau: true, about: 'Le trois-mâts pris dans la banquise depuis cent dix hivers, couché sur le flanc, sans son grand mât. Sa cale sert de grenier au lakou. Le capitaine est toujours à la barre.', x: 0.08, y: 0.7 },
  { id: 'lakou', nom: 'Le lakou Jean-Louis', ile: 'SNO 4', nouveau: true, about: 'Les cases de la famille, faites des planches du navire, autour d\'une cour où l\'on trace les vèvè à la cendre.', x: 0.32, y: 0.5 },
  { id: 'peristil', nom: 'Le péristyle', ile: 'SNO 4', nouveau: true, about: 'Le temple : un toit sans murs, et au milieu le poto mitan, le grand mât de La Délivrance planté dans la glace. Le vèvè du jour est tracé à sa base.', x: 0.36, y: 0.42 },
  { id: 'forge', nom: 'La forge d\'Ogou', ile: 'SNO 4', nouveau: true, about: 'Le seul feu jamais éteint de l\'île. Autour, la neige est grise de cendre ; c\'est là qu\'on prend la cendre des vèvè.', x: 0.28, y: 0.62 },
  { id: 'kalfou', nom: 'Le grand carrefour', ile: 'SNO 4', nouveau: true, about: 'Au milieu de l\'île, quatre pistes qui se croisent dans la neige. La nuit, les âmes qui attendent s\'y tiennent debout, des centaines, immobiles, et Mèt Kalfou au centre.', x: 0.52, y: 0.5 },
  { id: 'cimetiere', nom: 'Le cimetière du Baron', ile: 'SNO 4', nouveau: true, about: 'Des croix noires sous le givre, des tombes de neige tassée. Au centre, la croix de Baron ; à côté, celle de Brigitte, sur la tombe de Célimène. Des fils de givre entre les croix.', x: 0.62, y: 0.32 },
  { id: 'mapou', nom: 'Le mapou gelé', ile: 'SNO 4', nouveau: true, about: 'Un arbre qui ne devrait pas pousser ici, immense, gris de givre, mort et vivant à la fois. Damballah dort dans ses branches.', x: 0.7, y: 0.58 },
  { id: 'source', nom: 'La source de Simbi', ile: 'SNO 4', nouveau: true, about: 'Au nord, une eau chaude qui fume sous la glace, la seule qui ne gèle pas. On y voit le fond.', x: 0.56, y: 0.18 },
  { id: 'bouteilles', nom: 'La maison aux bouteilles', ile: 'SNO 4', nouveau: true, about: 'Sur la banquise, à l\'est : une maison de planches, et sous les avant-toits des centaines de bouteilles qui tintent au vent. Dans chacune, une âme.', x: 0.88, y: 0.46 },
  { id: 'marche', nom: 'Le marché d\'Ayizan', ile: 'SNO 4', nouveau: true, about: 'Sur la glace du port, des étals de planches où, à l\'heure qui devrait être l\'aube, vivants et morts échangent ce qu\'ils ont.', x: 0.4, y: 0.76 },
  { id: 'anbadlo', nom: 'Anba dlo, sous la banquise', ile: 'SNO 4', nouveau: true, about: 'Sous la glace de la mer, la lumière froide, les âmes qui descendent, La Sirène qui chante, et loin au fond le chemin vers Ginen.', x: 0.2, y: 0.88 },
];

// ── Les scénarios de SNO 4 ──
export const SCENARIOS_SNO4 = [
  // ── La trame ──
  {
    id: 'sno4-barriere', ile: 'SNO 4', rarete: 'trame', titre: 'Louvri baryè a', lieu: 'barriere', mythe: 'Vodou',
    quand: 'Au début, sur la grève.',
    recit: `Anaïse arrive à la Barrière avec le café de Legba, comme sa sœur il y a un an. Le vieil homme est assis sur son tonneau. Il faut le saluer en premier, toujours. Elle chante la prière ; les deux mâts givrés s'écartent d'un pixel, et le chemin s'ouvre dans la neige.`,
    lignes: [['anaise', 'Papa Legba, louvri baryè a pou mwen.'], ['legba', 'Ayibobo, pitit. Tu as apporté le café ?'], ['anaise', 'Il a gelé.'], ['legba', 'Ta sœur aussi me l\'apportait gelé. Je le buvais quand même.'], ['legba', 'La barrière est ouverte pour toi. Celle d\'en dessous, non.'], ['legba', 'Ce n\'est pas la mienne. Va voir mon autre visage. La nuit.']],
  },
  {
    id: 'sno4-kalfou', ile: 'SNO 4', rarete: 'trame', titre: 'Le carrefour plein', lieu: 'kalfou', mythe: 'Vodou',
    quand: 'La première nuit au grand carrefour.',
    recit: `Au croisement des quatre pistes, des centaines d'âmes debout dans la neige, pâles, immobiles, tournées vers le bas. Au centre, une grande silhouette sombre à l'œil rouge. Anisse est parmi les âmes, avec des enfants autour d'elle. Kalfou parle sans hâte, et il fixe son prix.`,
    lignes: [['kalfou', 'Les morts attendent chez moi.'], ['kalfou', 'Personne ne les a perdus. Personne ne les a rendus.'], ['anaise', 'Rends-moi ma sœur.'], ['kalfou', 'Je rouvrirai quand le roi d\'à côté lâchera son clou.'], ['kalfou', 'Ou si tu paies.'], ['anaise', 'Combien ?'], ['kalfou', 'Une nuit de ta vie. Tu ne sauras pas laquelle.'], ['anisse', 'Ne paie pas, Anaïse. Il compte mal, exprès.']],
  },
  {
    id: 'sno4-cimetiere', ile: 'SNO 4', rarete: 'trame', titre: 'Le cimetière sans fosse', lieu: 'cimetiere', mythe: 'Vodou',
    quand: 'En entrant dans le cimetière.',
    recit: `Les fils de givre vibrent sous les pas. Baron Samedi est assis sur sa propre croix, une jambe croisée, la pelle à côté, rangée. Il éclate de rire en la voyant. Maman Brigitte, à la tombe de Célimène, lève à peine la tête. Baron Cimetière compte, à voix basse.`,
    lignes: [['baron', 'Ha ! Une vivante ! Ça faisait longtemps. Entre, entre, on ne mord pas. Enfin, pas tous.'], ['baron', 'Pas un mort à enterrer depuis dix-neuf hivers, et pourtant ça meurt partout !'], ['cimetiere', 'Quatre cent douze ce matin. Quatre cent treize avec sa sœur.'], ['baron', 'Tu veux passer ta sœur ? Paie le passage.'], ['anaise', 'Avec quoi ?'], ['baron', 'Avec la vérité, ti fi. Qui devait porter le café, ce soir-là ?'], ['anaise', '… Moi.'], ['brigitte', 'Voilà. C\'était pas si dur. Viens là, toi. Tu as froid jusqu\'à l\'âme.']],
  },
  {
    id: 'sno4-forge', ile: 'SNO 4', rarete: 'trame', titre: 'Le feu d\'Ogou', lieu: 'forge', mythe: 'Vodou',
    quand: 'À la forge, avant de partir sur la banquise.',
    recit: `Le seul feu de l'île. Anaïse y verse du rhum en offrande ; les flammes montent, et Ogou la monte. Pendant vingt secondes, elle n'a plus froid, la machette pèse moins que rien, et elle parle fort. Quand il repart, elle a de la cendre plein les poches, de quoi tracer les vèvè.`,
    lignes: [['anaise', 'Ogou Feray, rhum sur le feu.'], ['ogou', 'Ha ! Voilà une fille qui sait recevoir !'], ['ogou', 'Lève le bras. Plus haut. Le froid, c\'est un ennemi comme un autre.'], ['ogou', 'Cette machette, je l\'ai tirée d\'un clou du navire. Elle connaît la mer et la glace.'], ['ogou', 'Prends la cendre. Trace droit. Et ne recule pas devant le vieux des bouteilles.']],
  },
  {
    id: 'sno4-zonbi', ile: 'SNO 4', rarete: 'trame', titre: 'Le sel', lieu: 'delivrance', mythe: 'Vodou',
    quand: 'Sur la banquise, entre l\'épave et la maison aux bouteilles.',
    recit: `Une femme passe, les yeux baissés, un fagot sur le dos, en répétant un mot. C'est Clotilde, la tante. On ne la frappe pas : on lui fait goûter le sel que Ti-Jo a donné. Elle tombe à genoux, puis parle trop vite, comme quelqu'un qui rattrape douze ans.`,
    lignes: [['clotilde', '… bwa … bwa …'], ['anaise', 'Tante Clotilde. Ouvre la bouche. C\'est du sel. De la part de Ti-Jo.'], ['clotilde', '(réveillée) Ti-Jo ? Où est Ti-Jo ? Quelle année ?'], ['clotilde', 'Non, ne me dis pas. Il a grandi. Je le sens.'], ['clotilde', 'Ton oncle a mon âme dans une bouteille bleue. La troisième à gauche de la porte.'], ['clotilde', 'Et il cherche ta sœur. Cours.']],
  },
  {
    id: 'sno4-bokor', ile: 'SNO 4', rarete: 'trame', titre: 'Deux-Mains', lieu: 'bouteilles', mythe: 'Vodou',
    quand: 'À la maison aux bouteilles.',
    recit: `Des centaines de bouteilles tintent sous l'avant-toit. Dans certaines, une lueur. Lucien ouvre la porte avant qu'on frappe ; il a l'air d'un homme de cinquante ans et il en a quatre-vingt-dix. Il ne se bat pas, il parle. Il est raisonnable, et c'est le pire. Erzulie Dantor arrive à la dernière ligne, et la neige se met à saigner.`,
    lignes: [['lucien', 'Entre, nièce. Tu as les yeux de ma sœur. Elle ne m\'a jamais regardé comme ça.'], ['lucien', 'Ta sœur ? Je peux la garder pour toi. Au chaud. Dans le verre.'], ['anaise', 'Tu as pris Clotilde.'], ['lucien', 'Je l\'ai gardée. Le dehors tue. Le verre conserve.'], ['lucien', 'Moi, mauvais ? J\'ai peur de mourir, c\'est tout. Comme toi. Comme le roi d\'à côté.'], ['dantor', 'Kè-kè-kè !'], ['lucien', 'Ah. Elle. Bon. On reparlera, nièce.']],
  },
  {
    id: 'sno4-anbadlo', ile: 'SNO 4', rarete: 'trame', titre: 'En bas de l\'eau', lieu: 'anbadlo', mythe: 'Vodou',
    quand: 'Par le trou de la source de Simbi, sous la banquise.',
    recit: `Simbi ouvre le passage d'eau chaude. Anaïse retient son souffle et descend sous la glace : une lumière froide, des âmes qui flottent, l'oncle Jean-Jacques qui rit avec des bulles, La Sirène qui chante. Agwe, en uniforme, s'excuse. On ne peut pas emmener Anisse plus bas : le passage vers Ginen est bouché, comme tout. On peut seulement la mettre dans un govi, pour qu'elle ne s'efface pas.`,
    lignes: [['simbi', 'Il y a toujours un passage sous la glace. Il est juste froid.'], ['jeanjacques', 'Tonton Jean-Jacques, à ton service. Retiens ton souffle.'], ['sirene', 'Viens en bas, ma belle. En bas, il fait moins froid qu\'on croit.'], ['agwe', 'Je vous ai menés à terre. Je ne savais pas qu\'elle était si froide.'], ['agwe', 'Le chemin de Ginen est bouché. Par une île qui ne veut pas mourir.'], ['anisse', 'Mets-moi dans la jarre. Je t\'attendrai dedans. Je chanterai, pour ne pas oublier.']],
  },
  {
    id: 'sno4-kari', ile: 'SNO 4', rarete: 'trame', titre: 'Le fils du roi au carrefour', lieu: 'kalfou', mythe: 'Vodou, Nord',
    quand: 'Quand Kári arrive à SNO 4 (sa saga et celle d\'Anaïse se croisent).',
    recit: `Un viking minuscule et noir arrive au carrefour par la piste du nord, une torche à la main, et toutes les âmes se tournent vers lui. Kalfou le reconnaît. Anaïse aussi, sans l'avoir jamais vu : c'est le fils du roi qui a cloué le temps. Chacun a la moitié de la réponse. Ils ne parlent pas la même langue ; Legba traduit.`,
    lignes: [['kalfou', 'Le fils du roi. Enfin.'], ['kari', 'Je cherche un clou.'], ['anaise', 'Je cherche ma sœur.'], ['legba', 'C\'est la même chose, mes enfants. Le clou tient la porte. La porte tient ta sœur.'], ['kari', 'Si je l\'arrache, mon père meurt.'], ['baron', 'Ha ! Enfin quelqu\'un qui comprend le problème !'], ['anaise', 'Alors on y va ensemble.']],
  },

  // ── Souvent ──
  {
    id: 'sno4-nibo', ile: 'SNO 4', rarete: 'souvent', titre: 'Le messager des morts', lieu: 'kalfou', mythe: 'Vodou',
    quand: 'Au carrefour, le jour (Kalfou n\'y est pas).',
    recit: `Un jeune homme poudré de cendre, un haut-de-forme trop grand, une bouteille de kleren aux piments, circule parmi les âmes et rapporte leurs messages, en les déformant pour rire. C'est par lui qu'Anaïse entend sa sœur le jour.`,
    lignes: [['nibo', 'Ta sœur te fait dire qu\'elle a froid aux pieds.'], ['nibo', 'Et que tu lui dois une écharpe. Et trois gourdes. Non, ça c\'est moi.'], ['anaise', 'Dis-lui que je viens.'], ['nibo', 'Elle le sait. Elle dit que tu es toujours en retard. Ha !']],
  },
  {
    id: 'sno4-fret', ile: 'SNO 4', rarete: 'souvent', titre: 'Gede Frèt', lieu: 'delivrance', mythe: 'Vodou (invention du jeu)',
    quand: 'Sur la banquise, quand la glace est mince.',
    recit: `Un jeune Gede givré, une moustache de glaçons, le haut-de-forme blanc de neige, chante une chanson de marin en claquant des dents. Il montre le chemin sur la glace mince : là où il marche, elle tient.`,
    lignes: [['gedefret', 'Brrr. Cent huit hivers que j\'ai froid. Et alors ? Je suis mort, pas malade.'], ['gedefret', 'Tu veux traverser ? Marche où je marche. Là. Non, là.'], ['gedefret', 'J\'étais sur la vergue, la nuit où on s\'est pris. Je faisais le guet. J\'ai bien vu la glace venir.'], ['gedefret', 'J\'ai crié. Personne n\'a entendu. Maintenant tout le monde m\'entend. Ha !']],
  },
  {
    id: 'sno4-vevelegba', ile: 'SNO 4', rarete: 'souvent', titre: 'Le premier vèvè', lieu: 'lakou', mythe: 'Vodou',
    quand: 'Dans la cour du lakou : le tutoriel des vèvè.',
    recit: `Sò Élise, depuis son govi, montre à Anaïse le vèvè de Legba, une croix avec une canne. Anaïse le marche dans la neige avec de la cendre ; quand le dessin se referme, la cour se tait et le vent tombe. Ti-Jo regarde, et il imite Baron pour faire rire.`,
    lignes: [['elise', 'Droit. Plus droit. Tu marches comme ton père.'], ['elise', 'Ferme le dessin. Un vèvè ouvert, c\'est une porte ouverte.'], ['tijo', 'Ha ! Ha ! Ti fi, tu traces comme un canard gelé ! … C\'est Baron qui dit, pas moi.'], ['elise', 'Ne prononce pas le nom de mon frère dans le péristyle. Dehors, si tu veux. Et crache après.']],
  },
  {
    id: 'sno4-freda', ile: 'SNO 4', rarete: 'souvent', titre: 'Le miroir de glace', lieu: 'peristil', mythe: 'Vodou, Nord',
    quand: 'Dans la chambre de Freda, au péristyle.',
    recit: `Une femme voilée se regarde dans un bloc de glace poli. Elle est belle, et pâle. Elle a rêvé de la grande Freya de SNO 7 et ne s'en remet pas. Elle pleure à la fin, comme toujours.`,
    lignes: [['freda', 'Tu m\'as apporté du parfum ? Il a gelé. Comme tout, ici.'], ['freda', 'J\'ai rêvé d\'une statue, dans l\'île d\'à côté. Freya, qu\'ils l\'appellent.'], ['freda', 'Elle a mon nom, presque. Mon visage, presque.'], ['freda', 'Presque, c\'est le pire.'], ['freda', '(elle pleure) Va. Va chercher ta sœur. Personne ne m\'a jamais cherchée comme ça.']],
  },
  {
    id: 'sno4-damballah', ile: 'SNO 4', rarete: 'souvent', titre: 'Le serpent blanc', lieu: 'mapou', mythe: 'Vodou',
    quand: 'Au mapou gelé, avec un œuf posé sur la farine.',
    recit: `Un œuf posé dans la neige sur un peu de farine. Le vent tombe sur toute l'île, une minute. Un serpent blanc descend du mapou ; Damballah monte Anaïse, qui rampe, siffle, et traverse le lac gelé sans le casser. Au-dessus, la nuit, une lueur se courbe : Ayida.`,
    lignes: [['damballah', 'Ssssss…'], ['damballah', 'Ssss… sss…'], ['marasa', '(traduisant) Il dit : tout ce qui est fermé a été ouvert une fois.'], ['marasa', 'Deux. Pas un. Deux.']],
  },
  {
    id: 'sno4-marche', ile: 'SNO 4', rarete: 'souvent', titre: 'Le marché d\'Ayizan', lieu: 'marche', mythe: 'Vodou',
    quand: 'À l\'heure qui devrait être l\'aube, sur la glace du port.',
    recit: `Des étals de planches, des vivants d'un côté, des morts de l'autre. On échange un souvenir contre un outil, un chant contre une poignée de sel. Ayizan surveille, une frange de sapin gelée à la main. Loko craque dans le mât. On peut y acheter la cendre, le café, les piments… et y vendre une chose qu'on regrettera.`,
    lignes: [['ayizan', 'Ici, on paie juste. Ni plus, ni moins.'], ['ayizan', 'Tu veux devenir mambo ? Alors tu brûleras un peu. Ici, ça fait du bien.'], ['loko', 'Le mât était un arbre, avant. Un arbre se souvient.'], ['ayizan', 'Ce mort-là vend la recette du café de Legba. Achète. Ta sœur la savait mieux que toi.']],
  },
  {
    id: 'sno4-cartes', ile: 'SNO 4', rarete: 'souvent', titre: 'La partie de cartes', lieu: 'cimetiere', mythe: 'Vodou, Étrusque',
    quand: 'Une nuit, sur un cercueil, au cimetière (ou à la taverne de Sidrún, sur SNO 8).',
    recit: `Baron Samedi et Vanth, la femme ailée à la torche, jouent aux cartes sur un cercueil. L'enjeu : les âmes en attente. Baron triche, Vanth le sait. Si Anaïse s'assoit à la table, elle peut jouer sa propre nuit contre l'âme de sa sœur.`,
    lignes: [['baron', 'Assieds-toi, ti fi. On joue les morts, ce soir.'], ['vanth', 'Il triche.'], ['baron', 'Elle le sait, chérie. C\'est pour ça qu\'elle revient.'], ['vanth', 'Je ne peux emmener personne, là-bas, sur l\'île du roi. Lui non plus. Alors on joue.'], ['baron', 'Mise ta peur, petite. C\'est la seule chose qu\'on accepte ici.']],
  },

  // ── Rare ──
  {
    id: 'sno4-capitaine', ile: 'SNO 4', rarete: 'rare', titre: 'La Délivrance appareille', lieu: 'delivrance', mythe: 'Vodou',
    quand: 'Une nuit où Agwe appelle.',
    recit: `L'épave craque de bout en bout, la banquise gémit, et pendant une minute La Délivrance se redresse dans la glace, voiles de givre gonflées. Le capitaine Toussaint crie ses ordres. Puis tout retombe. Le lendemain, une fissure longue comme l'île raye la banquise, vers le nord, vers SNO 7.`,
    lignes: [['toussaint', 'Larguez ! Larguez, je vous dis !'], ['toussaint', 'Cap au nord ! On rentre ! … Non. Au nord, c\'est le froid.'], ['agwe', 'Repose-toi, capitaine. Ce n\'est pas encore la marée.'], ['toussaint', '… Ah. La glace.']],
  },
  {
    id: 'sno4-dantor', ile: 'SNO 4', rarete: 'rare', titre: 'La neige qui saigne', lieu: 'lakou', mythe: 'Vodou',
    quand: 'Quand Lucien vient lui-même au lakou, une nuit.',
    recit: `Les bouteilles tintent de loin : le bokor approche. Mirlande se raidit, Dantor la monte. La mère tire le couteau, et la neige autour du lakou se met à rougir, un pixel après l'autre, en cercle. Lucien s'arrête au bord du cercle. Il n'entrera pas.`,
    lignes: [['lucien', 'Je viens en paix, belle-sœur. Je viens chercher ce qui se perd.'], ['dantor', 'Kè-kè-kè !'], ['mirlande', '(montée) Personne ne met ma fille en bouteille.'], ['lucien', 'Personne. Bien sûr. Bonne nuit.']],
  },

  // ── Les fins de SNO 4 ──
  {
    id: 'sno4-fin-passage', ile: 'SNO 4', rarete: 'fin', titre: 'Le passage', lieu: 'cimetiere', mythe: 'Vodou, Nord',
    quand: 'Quand Kári a arraché le clou sur SNO 7 (L\'Aube).',
    recit: `Au moment où le jour pâlit sur SNO 7, le carrefour de SNO 4 se met à bouger : les quatre cent treize âmes descendent, une à une, dans la neige, vers en bas de l'eau, vers Ginen. Baron reprend sa pelle et creuse en chantant, pour la première fois en dix-neuf hivers. Anisse se retourne une dernière fois.`,
    lignes: [['baron', 'Ha ! Au travail ! Masaka, ta pelle ! On a dix-neuf hivers de retard !'], ['anisse', 'Tu as trouvé ma moitié de café ?'], ['anaise', 'Je l\'ai bue. Elle était gelée.'], ['anisse', 'Alors on est quittes. Deux. Pas un. Deux.'], ['brigitte', 'Va, petite. Je la garde, là-bas. Elle chantera faux, et ce sera bien.'], ['masaka', 'Et la tombe du roi est prête. Je le savais.']],
  },
  {
    id: 'sno4-fin-bouteille', ile: 'SNO 4', rarete: 'fin', titre: 'La bouteille', lieu: 'bouteilles', mythe: 'Vodou',
    quand: 'Si Anaïse accepte l\'offre de Lucien pour garder sa sœur.',
    recit: `Anisse est dans le verre, au chaud, et elle chante. Anaïse a gagné une sœur pour toujours et perdu le droit d'entrer au péristyle. Lucien sourit. Au début de la partie suivante, il y a deux bouteilles de plus sous l'avant-toit, et une nouvelle bokor sur la banquise.`,
    lignes: [['lucien', 'Tu vois ? Ce n\'était pas si dur.'], ['anisse', '(dans le verre) Il fait chaud, ici. Pourquoi tu pleures ?'], ['baron', '… Celle-là, je ne la trouve pas drôle.']],
  },
  {
    id: 'sno4-fin-carrefour', ile: 'SNO 4', rarete: 'fin', titre: 'La mambo du carrefour', lieu: 'kalfou', mythe: 'Vodou',
    quand: 'Si Anaïse paie à Kalfou la nuit qu\'il demande.',
    recit: `Kalfou rouvre son carrefour pour Anisse seule. Anaïse a payé une nuit de sa vie sans savoir laquelle. Elle devient la mambo du carrefour : c'est elle, désormais, qui guide les morts de tout l'archipel jusqu'à la barrière. Dans les parties suivantes, sur SNO 7, une femme au foulard attend au bout de la piste des morts.`,
    lignes: [['kalfou', 'Payé.'], ['anaise', 'Quelle nuit ?'], ['kalfou', 'Tu le sauras ce soir-là.'], ['legba', 'Assieds-toi sur mon tonneau, ma fille. Il est à toi, maintenant, la moitié du temps.']],
  },
];

export const VOICES_SNO4 = {
  chwal: { nom: 'Le chwal', role: 'Celui ou celle qu\'un lwa monte, et qui traduit.' },
};
